name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # JVM_OPTS: "-Xmx6G" # ignored when .jvmopts is present
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'zulu'
          java-version: '25'
          #cache: No cache for release! We want clean and full release!

      - name: Setup sbt
        uses: sbt/setup-sbt@6158cb0903b8ceeae04f830055f3155e1b6a5ad7 # v1.5.11

      - name: Configure AWS Credentials (prod)
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare environment
        env:
          PRIVATE_REPOSITORY_SBT: ${{ vars.PRIVATE_REPOSITORY_SBT_2 }}
        run: |
          mkdir --parents ~/.sbt/1.0 || true
          echo "$PRIVATE_REPOSITORY_SBT" > ~/.sbt/1.0/privateRepository.sbt

      - name: Release
        id: release
        run: sbt "release with-defaults"

      - name: Publish on CodeArtifact (prod/us-east-1)
        env:
          DOMAIN: ${{ vars.AWS_CODEARTIFACT_DOMAIN }}
          DOMAIN_OWNER: ${{ vars.AWS_CODEARTIFACT_OWNER }}
          TAG: ${{ github.ref_name }}
        run: |
          VERSION="${TAG#v}"
          if [[ "$VERSION" =~ .*-M[0-9]+ ]]; then
            REPOSITORY="milestones"
          else
            REPOSITORY="releases"
          fi
          
          aws \
            --region us-east-1 \
            codeartifact update-package-versions-status \
            --domain "$DOMAIN" \
            --domain-owner "$DOMAIN_OWNER" \
            --repository "$REPOSITORY" \
            --format maven \
            --namespace io.gatling.enterprise \
            --package gatling-enterprise-api \
            --versions "$VERSION" \
            --target-status Published
